[general]
access-control-allow-origin="*"

[zookeeper]
servers=[ "zookeeper:2181" ]
timeout=6

[client-profile.kafka20]
kafka-version="0.10.1.0"
client-id="burrow-client"

[cluster.local]
class-name="kafka"
servers=[ "10.17.186.245:32783", "10.17.186.245:32784", "10.17.186.245:32785" ]
topic-refresh=60
offset-refresh=10

[consumer.consumer_kafka]
class-name="kafka"
cluster="local"
servers=[ "10.17.186.245:32783", "10.17.186.245:32784", "10.17.186.245:32785" ]
client-profile="kafka20"
start-latest=false
offsets-topic="__consumer_offsets"
group-blacklist="^(console-consumer-|python-kafka-consumer-).*$"

[consumer.consumer_zk]
class-name="kafka_zk"
cluster="local"
servers=[ "zookeeper:2181" ]
zookeeper-timeout=30
group-blacklist="^(console-consumer-|python-kafka-consumer-).*$"


[httpserver.default]
address=":8000"

[logging]
filename="/tmp/burrow.log"
level="debug"
maxsize=100
maxbackups=30
maxage=10
use-localtime=false
use-compression=true