version: '3.3'

services:
  kafka:
    # image: bitnami/kafka:2.1.0
    image: bitnami/kafka:2.0.0-debian-9
    ports:
     - '9092:9092'
    volumes:
      - ./:/opt/notebooks
      - ~/.jupyter:/home/appuser/.jupyter
      - ../data:/opt/data
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_BROKER_ID: 1
      KAFKA_NUM_NETWORK_THREADS: 3
      KAFKA_NUM_IO_THREADS: 8
      KAFKA_SOCKET_SEND_BUFFER_BYTES: 102400
      KAFKA_SOCKET_RECEIVE_BUFFER_BYTES: 102400
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 104857600
      KAFKA_LOGS_DIRS: /opt/bitnami/kafka/data
      KAFKA_DELETE_TOPIC_ENABLE: 'false'
      KAFKA_INTER_BROKER_LISTENER_NAME:
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_NUM_RECOVERY_THREADS_PER_DATA_DIR: 1
      KAFKA_MAX_MESSAGE_BYTES: 104857600
      KAFKA_LOG_FLUSH_INTERVAL_MESSAGES: 10000
      KAFKA_LOG_FLUSH_INTERVAL_MS: 1000
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_LOG_RETENTION_BYTES: 1073741824
      KAFKA_SEGMENT_BYTES: 1073741824
      KAFKA_LOG_RETENTION_CHECK_INTERVALS_MS: 300000
      KAFKA_LOG_MESSAGE_FORMAT_VERSION:
      KAFKA_ZOOKEEPER_CONNECT_TIMEOUT_MS: 6000
      KAFKA_INTER_BROKER_USER: admin
      KAFKA_INTER_BROKER_PASSWORD: bitnami
      KAFKA_BROKER_USER: user
      KAFKA_BROKER_PASSWORD: bitnami
      KAFKA_ZOOKEEPER_USER:
      KAFKA_ZOOKEEPER_PASSWORD:
      KAFKA_CERTIFICATE_PASSWORD:
      KAFKA_HEAP_OPTS: -Xmx4024m -Xms1024m
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on: 
      - zookeeper
  
  zookeeper:
    image: bitnami/zookeeper:3.4.12
    ports:
      - 2181:2181
    environment:
      ZOO_TICK_TIME: 2000
      ZOO_INIT_LIMIT: 10
      ZOO_SYNC_LIMIT: 5
      ZOO_MAX_CLIENT_CNXNS: 60
      ZOO_SERVERS:
      ZOO_CLIENT_USER:
      ZOO_CLIENT_PASSWORD:
      ZOO_SERVER_USERS:
      ZOO_SERVER_PASSWORDS:
      ZOO_ENABLE_AUTH: 'no'
      ZOO_HEAP_SIZE: 1024
      ALLOW_ANONYMOUS_LOGIN: 'yes'

networks:
  default:
    external:
      name: kafka-car0
