version: '3.3'

services:
  kafka:
    # image: bitnami/kafka:2.1.0
    # image: bitnami/kafka:2.0.0-debian-9
    image: wurstmeister/kafka:2.11-2.0.0
    ports:
      - '9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.17.186.245
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_HEAP_OPTS: -Xmx4024m -Xms1024m
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  

  zookeeper:
    image: bitnami/zookeeper:3.4.12
    ports:
      - 2181:2181
    environment:
      ZOO_TICK_TIME: 2000
      ZOO_INIT_LIMIT: 10
      ZOO_SYNC_LIMIT: 5
      ZOO_MAX_CLIENT_CNXNS: 60
      ZOO_SERVERS:
      ZOO_CLIENT_USER:
      ZOO_CLIENT_PASSWORD:
      ZOO_SERVER_USERS:
      ZOO_SERVER_PASSWORDS:
      ZOO_ENABLE_AUTH: 'no'
      ZOO_HEAP_SIZE: 1024
      ALLOW_ANONYMOUS_LOGIN: 'yes'

  burrow:
    image: joway/docker-burrow
    ports:
      - 8000:8000
    volumes:
      - ${PWD}/burrow.toml:/etc/burrow/burrow.toml
      - ${PWD}/http-influxdb.tmpl:/etc/burrow/http-influxdb.tmpl

  bui:
    image: joway/burrow-dashboard
    ports:
      - 8181:80
    environment:
      BURROW_BACKEND: http://10.17.186.245:8000

  influx:
    image: influxdb:1.5
    ports:
      - 8086:8086
    environment:
      INFLUXDB_DB: kafka
      INFLUXDB_WRITE_USER: kafka
      INFLUXDB_WRITE_USER_PASSWORD: kafka
      INFLUXDB_ADMIN_PASSWORD: supersecretpassword
  
  grafana:
    image: grafana/grafana:5.4.2
    ports:
      - "3000:3000"
    environment:
    - GF_SECURITY_ADMIN_PASSWORD=admin


networks:
  default:
    external:
      name: kafka-car0
